### ISSUE TITLE
confirmation of power setting fails on first try

### ISSUE THREAD

**Issue by jeffkowalski** [SOTAmat/SOTAcat#47]
Presently, when adjusting power in the "CAT" tab, there is a retry in confirming the power setting.  The log says:
```
I (76185) sc:hdl_cat.: setting power to '0'
E (76285) sc:kx_radio: bad result from command 'PC;' after 94.428 ms, returned bytes=0, out_buff=\0\0\0\0\0\0...
I (76285) sc:kx_radio: Retrying...
I (76455) sc:kx_radio: command 'PC' successful; value = 0
```
This is likely because the power command takes a moment on the radio to really settle.  Best to empirically determine that figure and add a delay between setting and confirming, to eliminate the unsightly retry.

**Comment by brianmathews** [comment]
The KX3 is a bit different than the KX2.  The KX3 has a special low power mode that is engaged < 3.2 watts and you can hear a relay switch when you cross that threshold.  I suspect that the KX2 and KX3 will have different timings when changing power levels due to that extra relay action taking time.  I am surprised that the power change takes over 100ms on a KX2.
